Revert "fix: appleclang-15 timeout on compilation workaround"
This reverts commit 7d340d90988c60f72034e8afdb457bb6529d0636.

This fix was causing the following error:

```
fatal error: error in backend: SmallVector unable to grow.
```